[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pacodexion"
version = "0.2.0"
description = "Runner and validator for Codexion project test cases."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "pacodexion" }]
dependencies = []

[project.scripts]
pacodexion = "pacodexion.__main__:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
